package funs;

public class InterOperaWithJava {

    public static void main(String... args) {
        //NumUtils is the name given to the class generated by Kotlin
        //We can use annotations to tell Kotlin how to generate the resulting classes
        System.out.println(MyUtils.max(6,5));

        //Kotlin overloads the method so that the default parameters work from Jav
        MyUtils.log("Yeah!!");
        MyUtils.log("Yeah!!", 3);


    }
}
